[workspace]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["conda-forge"]
name = "gisruk2025"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
momepy = ">=0.9.1,<0.10"
geopandas = ">=1.0.1,<2"
shapely = ">=2.1.0,<3"
scikit-learn = ">=1.6.1,<2"
numba = ">=0.61.2,<0.62"
seaborn = ">=0.13.2,<0.14"
pyarrow = ">=19.0.0,<20"
duckdb = ">=1.2.1,<2"
pooch = ">=1.8.2,<2"
rich = ">=14.0.0,<15"
fsspec = ">=2025.3.2,<2026"
geopy = ">=2.4.1,<3"
jupyterlab = ">=4.4.0,<5"

[pypi-dependencies]
overturemaestro = ">=0.3.2, <0.4"
geoplanar = ">=0.4.0, <0.5"
neatnet = ">=0.0.4, <0.0.5"
