[workspace]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["conda-forge"]
name = "gisruk2025"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
momepy = ">=0.9.1,<0.10"
geopandas = ">=1.0.1,<2"
shapely = ">=2.1.0,<3"
scikit-learn = ">=1.6.1,<2"
numba = ">=0.61.2,<0.62"
jupyterlab = ">=4.4.0,<5"
ipywidgets = ">=8.1.6,<9"
osmnx = ">=2.0.2,<3"
geopy = ">=2.4.1,<3"
clustergram = ">=0.8.1,<0.9"
bokeh = ">=3.7.2,<4"
ruff = ">=0.11.5,<0.12"

[pypi-dependencies]
geoplanar = ">=0.4.0, <0.5"
neatnet = ">=0.0.5, <0.0.6"
